In [60]:
import numpy as np

In [61]:
arr = np.arange(-10,101,10)

In [62]:
arr

array([-10,   0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [63]:
arrr = np.ones(3)

In [64]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [65]:
arr = np.zeros((4,3))

In [66]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
arr = np.eye(4)

In [68]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
#Chapter 1.6 Using a random method
arr = np.random.rand(5)#Numeros aleatorios entre el (0,1) Distribucion uniforme se le conoce cuando se generan numeros aleatorios     


In [70]:
arr

array([0.45894429, 0.03315866, 0.14011867, 0.36827258, 0.09969132])

In [71]:
arr = np.random.rand(3,4)#Genra numeros aleatorios entre el 0 y el 1

In [72]:
arr

array([[0.61499197, 0.21114282, 0.85486074, 0.24339004],
       [0.33135148, 0.89842479, 0.95857268, 0.86954469],
       [0.31596154, 0.75218901, 0.29211188, 0.86321171]])

In [73]:
arr = np.random.randn(6)#Esta genera nueros aleatorios con una distribución normal pegados al cero 

In [74]:
arr

array([ 0.11530053, -0.7455593 ,  2.83663   , -0.84047453, -0.67493923,
        0.76701614])

In [75]:
arr = np.random.randn(4,3)#Creamos una matriz

In [76]:
arr

array([[-1.79252806e-01, -5.38490447e-01,  1.97215361e+00],
       [ 6.72518283e-01, -2.24122435e+00, -1.86785253e-03],
       [ 4.71296702e-01, -1.14912828e+00,  1.07669049e+00],
       [-1.44032979e-02,  7.38888380e-01,  4.63859209e-01]])

In [77]:

#Genera numeros aleatrios del 0 al 10 generara 5 numeros aleatorios
arr = np.random.randint(0,11,(3,4))#Generar Numeros aleatorios del tipo entero

In [78]:
arr

array([[ 8, 10,  3,  0],
       [ 1, 10,  6,  1],
       [ 7,  3, 10,  9]])

In [79]:
arr = np.array([[2,8,-3],
                [3,-1,0],
                [2,5,2],
               [1,3,4]])

In [80]:
arr

array([[ 2,  8, -3],
       [ 3, -1,  0],
       [ 2,  5,  2],
       [ 1,  3,  4]])

In [81]:
arr.reshape(3,4)#Convierte un arreglo en matriz
#3 filas y 4 columnas 

array([[ 2,  8, -3,  3],
       [-1,  0,  2,  5],
       [ 2,  1,  3,  4]])

In [82]:
#Crear un arreglo de numpy de los numeros 5,10,15,20
arreglo = np.array([5,10,15,20])
arreglo

array([ 5, 10, 15, 20])

In [83]:
#Genera un arreglo con valores  desde 0 hasta 9
arreglo = np.arange(10)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
#crea un arreglo de tamaño 5 lleno de 1s
arreglo = np.ones(5)
arreglo

array([1., 1., 1., 1., 1.])

In [85]:
#Genera una matriz de ceros de tamaño 3 * 3
arreglo = np.zeros((3,3))
arreglo

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
#Crea una matriz identidad de 4 * 4
arreglo = np.eye(4)
arreglo

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
#Genera una arreglo con 5 numeros aleatorios entre 0 y 1
arreglo = np.random.rand(5)
arreglo

array([0.5651056 , 0.71921708, 0.99319232, 0.97336308, 0.27376511])

In [88]:
#Crea una matriz de 2 * 2 convalores aleatorios de una distribucion de desviacion estandar  1
arreglo = np.random.randn(2,2)
arreglo

array([[-0.24282198, -0.81392191],
       [-0.53547949,  0.92989275]])

In [89]:
#crea un arreglo con 3 enteros aleatorios entre 1 y 10
arreglo = np.random.randint(1,10,3)
arreglo

array([7, 1, 6])

In [90]:
#Array indexing and slicing
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr[3]#Buscar en un arreglo mediante el index

np.int64(4)

In [92]:
arr[2:7]#Buscar en un arreglo mediante el index entre cierto rango de números

array([3, 4, 5, 6, 7])

In [93]:
arr[:4]#Seleccionar del 0 al 5 

array([1, 2, 3, 4])

In [94]:
arr[2:]#Seleccionar hasta el ultimo valor en un arreglo

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]
#Convertir arreglos en una sola matriz
arr = np.array([row1,row2,row3])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
#Filas-Columnas
arr[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
#Mostrar solo ciertas columnas
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [98]:
#Que aparezcan las ultimas dos filas 
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [99]:
#Que aparezcan solo 5,6,8,9
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [100]:
#5. Numpy for Aritmetic operation
#5.1 Square roots, Square
lista = [10,20,30,40,50]
arr = np.sqrt(lista)
arr

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [101]:
#Eleva al cuadrado cada elemento de la lista
arr = np.square(lista)
arr

array([ 100,  400,  900, 1600, 2500])

In [102]:
#5,2 Log base 10, log natural
arr = np.log10(lista)
arr

array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ])

In [103]:
arr = np.log(lista)
arr

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [104]:
#5.3 Exponencial
arr = np.exp(lista)
arr

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [105]:
#5.4 Seno and coseno
arr = np.sin(lista)
arr


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [106]:
arr = np.cos(lista)
arr

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [107]:
#Distribucion normal Es la distribucion gaussiana
#Crear una matriz de identidad de orden 3*3 llamada A
#Genere un vector con 3 valores aleatorios de distribucion gaussiana,llamada "v"
#multiplicar vector v por matriz A
#genere una matriz de unos de orden 3*4, llamada c
#genere una matriz de orden 4*3 con valores aleaotorios entre 1 al 50, llamada D
#Haga la siguiente operación (2A*C)*D+At

In [108]:
#1
A = np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
#2
V = np.random.randn(3)
V

array([ 1.73610409,  0.13102132, -1.81550757])

In [110]:
mult = A * V
mult

array([[ 1.73610409,  0.        , -0.        ],
       [ 0.        ,  0.13102132, -0.        ],
       [ 0.        ,  0.        , -1.81550757]])

In [111]:
#3
C = np.ones([3,4])
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [112]:
D = np.random.randint(1,51,[4,3])
D

array([[26, 21, 40],
       [18, 38, 47],
       [13, 11, 48],
       [35, 17, 39]])

In [113]:
res = (2 * A * C) * D + A.T

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [ ]:
#19/11/2024
import numpy as np
matrizA = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
matrizB = np.array([[10,11,12],
                    [13,14,15],
                    [16,17,18]])

In [ ]:
arr = np.dot(matrizA,matrizB)#Multiplicar
arr

In [ ]:
#Producto elemento por elemento 
arr = matrizA * matrizB
arr

In [ ]:
arr = np.multiply(matrizA,matrizB)
arr

In [ ]:
#Matriz inversa
arr = np.linalg.inv(matrizA)
arr

In [ ]:
#determinante 
arr = np.linalg.det(matrizA)
arr

In [ ]:
#Traza de una matriz(Es la suma de los elementos en diagonal)
matrizA
arr = np.trace(matrizA)
arr

In [ ]:
#Funciones estadisticas y más
#Suma
arr = np.array([1,2,3,4,5])
arr
suma = np.sum(arr)
suma


In [ ]:
#Minimo de todos los elementos de un arreglo
minimo = np.min(arr)
minimo

In [ ]:
#Max
max = np.max(arr)
max

In [ ]:
#Promedio
promedio = np.mean(arr)
promedio

In [ ]:
#Desviacion estandar
desv_est = np.std(arr)
desv_est

In [ ]:
#Varianza
varianza = np.var(arr)
varianza

In [ ]:
#Mediana
media = np.median(arr)
media

In [ ]:
#sumar las filas de la matriz A
suma = np.sum(matrizA,axis = 0)
suma

In [ ]:
#sumar las columnas de la matriz A
suma = np.sum(matrizA,axis = 1)
suma

In [ ]:
#sumar Todos los elementos de la matriz A
suma = np.sum(matrizA)
suma

In [ ]:
maximo = np.max(matrizA)
maximo

In [ ]:
minimo = np.min(matrizA)
minimo

In [ ]:
promedio = np.mean(matrizA)
promedio