In [133]:
import numpy as np

In [134]:
A = np.array([[4, 5, 6], 
            [1, 2, 3], 
            [7, 8, 9], 
            [10, 11, 12]])
A

array([[ 4,  5,  6],
       [ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [135]:
#Inciso A

B = A.T
B

array([[ 4,  1,  7, 10],
       [ 5,  2,  8, 11],
       [ 6,  3,  9, 12]])

In [136]:
#Inciso B

C = A.reshape(4,3)
C


array([[ 4,  5,  6],
       [ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [137]:
#Inciso C

D = B.dot(C)
D

array([[166, 188, 210],
       [188, 214, 240],
       [210, 240, 270]])

In [138]:
#Inciso D

E = np.eye(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
#Inceiso E

F = D.dot(E)
F

array([[166., 188., 210.],
       [188., 214., 240.],
       [210., 240., 270.]])

In [140]:
#Inciso F
# Crea un vector del 0 al 100 con saltos de 2 en 2 e incluye el 100

G = np.arange(0,101,2)
G

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [141]:
#Inciso G
#Crea una matriz de 3x4 de numeros aleatorios distribuidos uniformemente.[0,1]
g = np.random.rand(3,4)
g


array([[0.12459207, 0.38870437, 0.03600515, 0.29039295],
       [0.43770249, 0.85204215, 0.53545913, 0.82145469],
       [0.91348584, 0.61304107, 0.88313442, 0.64112745]])

In [142]:
#Inciso H
# Crea una matriz de 4x3 de numeros aleatorios con dist normal
h = np.random.randn(4,3)
h

array([[-0.25823552, -0.85389711, -3.64237252],
       [ 0.71965236, -1.27746131, -1.33278308],
       [ 0.11071221, -0.89649431, -0.55977161],
       [-0.27034737, -0.7751646 , -0.60911194]])

In [143]:
# Inciso I
# Crea una matriz de 3x3 con numeros aleatorios del 0 al 20
i = np.random.randint(0,21,size = (3,3))
i

array([[13,  0,  0],
       [ 4, 18,  7],
       [ 0, 16, 19]])

In [144]:
#Inciso J
# Inversa matriz D
j 
j

<module 'numpy' from '/Users/memopispo/Documents/NumpyPandas/.venv/lib/python3.11/site-packages/numpy/__init__.py'>

In [145]:
# Inciso K
# det D
ka = np.diag(D)
ka

array([166, 214, 270])

In [146]:
# Inciso l 
# traza de D
l = np.trace(D)
l

np.int64(650)

In [147]:
# Inciso m
#suma
suma  = np.sum(D)
suma




np.int64(1926)

In [148]:
#min
min = D.min()
min

np.int64(166)

In [149]:
#max
max = D.max()
max


np.int64(270)

In [150]:
#desviacion estandar


In [151]:
#promedio de D
prom = np.average(D)
prom

np.float64(214.0)

In [152]:
#Inciso n
#Suma de filas de D
n1 = np.sum(D)
n1


np.int64(1926)

In [153]:
#Inciso o
#suma de columnas de D
o = np.sum(D)
o

np.int64(1926)